### ISSUE TITLE
which c++ version should I install

### ISSUE THREAD

**Issue by deepocean-tech** [msu-graphics-group/LiteTF#1]
Hi, When I make this project ,I get this error 
[root@localhost LiteTF]# make -j8
[  7%] Building CXX object CMakeFiles/nn_test.dir/direct/tensors.cpp.o
[ 14%] Building CXX object CMakeFiles/nn_test.dir/direct/neural_network.cpp.o
[ 21%] Building CXX object CMakeFiles/nn_test.dir/direct/siren.cpp.o
[ 28%] Building CXX object CMakeFiles/nn_test.dir/direct/nnd_tests.cpp.o
[ 35%] Building CXX object CMakeFiles/nn_test.dir/tensor_processor.cpp.o
[ 42%] Building CXX object CMakeFiles/nn_test.dir/tensor_processor_impl.cpp.o
[ 50%] Building CXX object CMakeFiles/nn_test.dir/tensor_compiler.cpp.o
[ 57%] Building CXX object CMakeFiles/nn_test.dir/neural_network.cpp.o
In file included from /opt/soft/LiteTF/direct/tensors.cpp:1:0:
/opt/soft/LiteTF/direct/tensors.cpp: In function ‘void nnd::print(const nnd::TensorView&)’:
/opt/soft/LiteTF/direct/tensors.cpp:106:21: warning: ‘if constexpr’ only available with -std=c++1z or -std=gnu++1z
                  if constexpr (std::is_floating_point<ValueType>::value)
                     ^
/opt/soft/LiteTF/direct/tensors.h:129:7: note: in definition of macro ‘TV_ITERATE’
       F                                                        \
       ^
In file included from /opt/soft/LiteTF/neural_network.cpp:1:0:
/opt/soft/LiteTF/neural_network.h:292:26: error: ‘variant’ in namespace ‘std’ does not name a template type
   using Optimizer = std::variant<OptimizerGD, OptimizerAdam>;
                          ^~~~~~~
/opt/soft/LiteTF/neural_network.h:329:50: error: ‘Optimizer’ has not been declared
     TensorProgram get_train_prog(int batch_size, Optimizer optimizer, Loss loss);
                                                  ^~~~~~~~~
/opt/soft/LiteTF/neural_network.h:331:48: error: ‘Optimizer’ has not been declared
                int batch_size, int iterations, Optimizer optimizer, Loss loss, bool verbose = false);
                                                ^~~~~~~~~
/opt/soft/LiteTF/neural_network.h:332:126: error: ‘Optimizer’ has not been declared
     void train(const float *data, const float *labels, int samples, int batch_size, int epochs, bool use_validation = false, Optimizer optimizer = OptimizerAdam(0.01f),
                                                                                                                              ^~~~~~~~~
/opt/soft/LiteTF/neural_network.h:332:148: error: could not convert ‘nn::OptimizerAdam(9.99999978e-3f, ((float)9.0000000000000002e-1), ((float)9.99e-1), ((float)1.0e-8))’ from ‘nn::OptimizerAdam’ to ‘int’
     void train(const float *data, const float *labels, int samples, int batch_size, int epochs, bool use_validation = false, Optimizer optimizer = OptimizerAdam(0.01f),
                                                                                                                                                    ^~~~~~~~~~~~~~~~~~~~
[ 64%] Building CXX object CMakeFiles/nn_test.dir/tensor_token.cpp.o
/opt/soft/LiteTF/neural_network.cpp:256:63: error: ‘Optimizer’ has not been declared
   TensorProgram NeuralNetwork::get_train_prog(int batch_size, Optimizer optimizer, Loss loss)
                                                               ^~~~~~~~~
/opt/soft/LiteTF/neural_network.cpp: In member function ‘nn::TensorProgram nn::NeuralNetwork::get_train_prog(int, int, nn::Loss)’:
/opt/soft/LiteTF/neural_network.cpp:325:14: error: ‘holds_alternative’ is not a member of ‘std’
     if (std::holds_alternative<OptimizerGD>(optimizer))
              ^~~~~~~~~~~~~~~~~
/opt/soft/LiteTF/neural_network.cpp:325:43: error: expected primary-expression before ‘>’ token
     if (std::holds_alternative<OptimizerGD>(optimizer))
                                           ^
/opt/soft/LiteTF/neural_network.cpp:327:56: error: no matching function for call to ‘get<nn::OptimizerGD>(int&)’
       OptimizerGD opt = std::get<OptimizerGD>(optimizer);
                                                        ^
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/tuple:38:0,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_map.h:63,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/map:61,
                 from /opt/soft/LiteTF/tensor_processor.h:4,
                 from /opt/soft/LiteTF/tensor_compiler.h:2,
                 from /opt/soft/LiteTF/neural_network.h:2,
                 from /opt/soft/LiteTF/neural_network.cpp:1:
/opt/rh/devtoolset-7/root/usr/include/c++/7/utility:229:5: note: candidate: template<long unsigned int _Int, class _Tp1, class _Tp2> constexpr typename std::tuple_element<_Int, std::pair<_Tp1, _Tp2> >::type& std::get(std::pair<_Tp1, _Tp2>&)
     get(std::pair<_Tp1, _Tp2>& __in) noexcept
I run the make -j8 command, I install c++17 in my centos computer
can u help me

**Comment by SammaelA** [comment]
Hi!
C++17 is required. You should try explicitly add " -std=c++17" to compiler arguments, it should help. Also worth checking what version of compiler is used by default on your computer and if it supports c++17 at all.
